---
title: "Article 4: Directors, Election and Removal"
---

## **4.1 – POWERS**

The Corporation shall have a Board of Directors (referred to, in these bylaws, as the "Board"). The activities and affairs of the Corporation shall be conducted and all corporate powers shall be exercised by or under the direction of the Board, acting as a body. The Board may delegate the management of the activities of the Corporation to any person or persons, management company, or committee however composed, provided that the activities and affairs of the Corporation shall be managed and all corporate powers shall be exercised under the ultimate direction of the Board.


## **4.2 - NUMBER AND CLASSES**

### **4.2.1**

There shall be two classes of directors, known as "Plenary Directors" and "At Large Directors." The Board shall have not less than nine directors (including the Plenary Directors as set forth below) nor more than 15 directors. The precise number of directors shall be fixed within these limits by an affirmative vote of a majority of the directors then in office. The authorized number of directors at the time of adoption of these amended and restated bylaws is nine.

## **4.2.2**

The Plenary Directors are the President, Vice-President, and a chair from each of the Administrative Committees as detailed in the [Policies and Procedures](https://github.com/ESIPFed/Governance/blob/master/ESIP%20Policies%20and%20Procedures/1.0%20Corporate/ESIP%20P%26P%201.3%20Corporate%20Organization.md#section-5----administrative-committees). In addition to their duties and obligations as directors, the Plenary Directors shall have the duties set forth below and such other duties as set forth in the Policies and Procedures Document:

   **4.2.2.1** - The President presides over all meetings of members (including members' business meetings and the January and July Meetings, but not Board meeting) and any other public meetings of the corporation, and chairs the Program Committee.  
   **4.2.2.2** - The Vice-President serves the duties of the President in the President's absence or in ability to serve.  
   **4.2.2.3** - The committee chairs lead the respective advisory committees. The responsibilities of the advisory committees are determined by the Board as set forth in the [Policies and Procedures Document](https://github.com/ESIPFed/Governance/blob/master/ESIP%20Policies%20and%20Procedures/1.0%20Corporate/ESIP%20P%26P%201.3%20Corporate%20Organization.md#section-5----administrative-committees).


## **4.3 - ELECTION AND TERM OF OFFICE OF DIRECTORS**

### **4.3.1**

Plenary Directors shall be elected at each annual members' business meeting to terms of one year. 

### **4.3.2**

At Large Directors shall be elected to terms of office of two years; provided, however, that at the first annual members' business meeting following adoption of these Amended and Restated Bylaws, one At Large Director shall be elected to an initial term of one year and two shall be elected to an initial term of two years. Following the expiration of these initial terms, the terms of office of At Large Directors subsequently elected shall be two years. At all times, the number of At Large Directors designated for each term shall be equal to two or as equal as possible to two if the number of authorized directors is not evenly divisible by two. 

### **4.3.3**

All terms of office of directors shall run from the date of the annual members' business meeting at which the Director was elected until the date of the annual members' business coinciding with the conclusion of their respective term of office. Directors shall be elected at each annual meeting to fill those terms that expire at that annual meeting. If the directors are not elected at an annual meeting at which elections are to be held per these bylaws, they may be elected at any other regular meeting or at any special meeting held for that purpose (which need not be the exclusive purpose of that meeting).

## **4.3.4**

Each director, including a director elected to fill a vacancy or elected at a special meeting, shall hold office until expiration of the term for which elected and until a successor has been elected and qualified.


## **4.4 – NOMINATIONS**

Qualified candidates for election to the Board shall be nominated as described in the [Policies and Procedures Document](
https://github.com/ESIPFed/Governance/blob/master/ESIP%20Policies%20and%20Procedures/1.0%20Corporate/ESIP%20P%26P%201.3%20Corporate%20Organization.md#part-1----nominating-committee-electing-volunteer-leaders).


## **4.5 - REMOVAL OF DIRECTORS**

### **4.5.1**

The Board may declare vacant the office of a director who has been declared of unsound mind by a final order of court, or convicted of a felony, or been found by a final order or judgment of any court to have breached any duty under the Act.

### **4.5.2**

A director may be removed with or without cause by the vote of a majority of the members present and voting, provided that such action is taken at a meeting of the Board called expressly for that purpose.

### **4.5.3**

The Superior Court may remove a director from office in a proceeding commenced by or in the right of the Corporation to the extent permitted by Section 29–406.09 of the Act.


## **4.6 – VACANCIES**

### **4.6.1**

Vacancies on the Board shall exist:

   **4.6.1.1** - On the death or resignation of any director;  
   **4.6.1.2** - Whenever the number of authorized directors is increased;  
   **4.6.1.3** - Upon a failure of the members, at any members’ business meeting at which any director or directors are to be elected, to elect the number of directors required to be elected at that meeting;
   **4.6.1.4** - On the vote of the members to remove any director(s); or  
   **4.6.1.5** - On the declaration by Board resolution of a vacancy in the office of a director who has been declared of unsound mind by a final order of court, or convicted of a felony, or been found by a final order or judgment of any court to have breached any duty under Section 29–406 et seq. of the Act.

### **4.6.2**

Any director may resign effective upon giving written notice to the Chairman or the Secretary. Any such resignation shall take effect at the date of receipt of such notice or at any later date specified therein. Unless otherwise specified therein, the acceptance of such resignation shall not be necessary to make it effective.

### **4.6.3**

A reduction of the number of authorized directors shall be effective only upon the expiration of the then current directors' terms of office or upon the occurrence of any other vacancy in the Board, unless the reduction or the amendment also provides for the removal of one or more specified directors.

### **4.6.4**

Except for a vacancy resulting from an increase in the number of directors, vacancies on the Board shall be filled by a vote of the members during the during the first three months after the vacancy occurs.

### **4.6.5**

A person elected to fill a vacancy as provided by this Section shall hold office until the next election of the Board or until his or her death, resignation or removal from office.


