---
title: "Article 10: Corporate Records, Reports and Seal"
---

## **10.1 – MAINTENANCE OF CORPORATE RECORDS**

The Corporation shall keep at its principal office:

### **10.1.1**

Minutes of all meetings of directors and committees of the Board, indicating the time and place of holding such meetings, whether regular or special, how called, the notice given, and the names of those present and the proceedings thereof for the past three years;

### **10.1.2**

A copy of the Corporation's Articles of Incorporation and these bylaws as amended to date;

### **10.1.3**

Copies of all filings made to the Internal Revenue Service, the District of Columbia Department of Consumer and Regulatory Affairs, and the District of Columbia Office of Tax and Revenue that the corporation is required, by statute or regulation, to make generally available to the public;

### **10.1.4**

All communications in the form of a record to members generally within the past three years, including the financial statements furnished for the past three years;

### **10.1.5**

A list of the names and business addresses of its current directors and officers; and

### **10.1.6**

Its most recent biennial report delivered to the Mayor under section 29 102.11 of the Act.



## **10.2 - CORPORATE SEAL**

The Board may adopt, use, and at will alter, a corporate seal. Such seal shall be kept at the principal office of the Corporation. Failure to affix the seal to corporate instruments, however, shall not affect the validity of any such instrument.


## **10.3 - DIRECTORS' INSPECTION RIGHTS**

Every director shall be entitled to inspect and copy the books, records, and documents of the corporation at any reasonable time to the extent reasonably related to the performance of the director's duties as a director, including duties as a member of a committee, but not for any other purpose or in any manner that would violate any duty to the corporation or law other than this chapter.


## **10.4 - MEMBERS' INSPECTION RIGHTS**

### **10.4.1**

A member of the Corporation shall be entitled to inspect and copy, during regular business hours at the Corporation's principal office, any of the records of the corporation described listed below, if the member delivers to the corporation a signed notice in the form of a record at least five business days before the date on which the member wishes to inspect and copy, subject to Section 10.4.2. The records the member may inspect include:

   **10.4.1.1** - Excerpts from any records required to be maintained under [Section 10.1.1](https://github.com/ESIPFed/Governance/blob/master/Bylaws/Article%2010%20Corporate%20records%2C%20reports%20and%20seal/10.01%20Maintenance%20of%20corporate%20records.md#1011), to the extent not subject to inspection under Section 10.4.1;  

   **10.4.1.2** - Accounting records of the corporation; and  
   **10.4.1.3** - The membership list; provided, however, the Corporation may comply at its expense with a member's demand to inspect the record of members by providing the member with a list of members that was compiled no earlier than the date of the member's demand.

### **10.4.2**

A member may inspect and copy the records described in Section 10.4.2 only if: 

   **10.4.2.1** - The member's demand is made in good faith and for a proper purpose;  
   **10.4.2.2** - The member describes with reasonable particularity the purpose and the records the member desires to inspect; and  
   **10.4.2.3** - The records are directly connected with this purpose.

### **10.4.3**

Copies under this section may be provided an electronic transmission if available and requested by the member.

### **10.4.4**

The Corporation may impose a reasonable charge, covering the costs of labor and material, for copies of any documents provided to the member. The charge shall not exceed the estimated cost of production, reproduction, or transmission of the records.

### **10.4.5**

A member's agent or attorney shall have the same inspection and copying rights as the member.

### **10.4.6**

The Corporation may, within 10 business days after receiving a demand under this Section, make a written offer of an alternative method if reasonable and timely achievement of the proper purpose specified in the demand without providing access to or a copy of the membership list. Any rejection of this offer must be in writing and must state the reasons the proposed alternative does not meet the proper purpose of the demand.

### **10.4.7**

Any inspection and copying under this Section may be made in person or by the member's agent or attorney. The right of inspection includes the right to copy and make extracts. This right of inspection extends to the records of any subsidiary of the Corporation.

### **10.4.8**

The right of inspection granted by this section may not be abolished or limited by a nonprofit corporation’s Articles of Incorporation or bylaws.


## **10.5 - ANNUAL FINANCIAL STATEMENTS**

### **10.5.1**

Upon written demand from a member, the Corporation shall furnish that member with its latest annual financial statements, which may be consolidated or combined statements of the Corporation and one or more of its subsidiaries, as appropriate, that include a balance sheet as of the end of the fiscal year and a statement of operations for the year. If financial statements are prepared for the Corporation on the basis of generally accepted accounting principles, the annual financial statements shall also be prepared on that basis. The Corporation may impose a reasonable charge for copying the report.

### **10.5.2**

If the annual financial statements are reported upon by a certified public accountant, the accountant’s report must accompany them. If not, the statements shall be accompanied by a statement of the Chairman or the person responsible for the Corporation’s accounting records:

   **10.5.2.1** - Stating the reasonable belief of the president or other person as to whether the statements were prepared on the basis of generally accepted accounting principles and, if not, describing the basis of preparation; and  
   **10.5.2.2** - Describing any respects in which the statements were not prepared on a basis of accounting consistent with the statements prepared for the preceding year.


