---
title: "Article 7: Officers"
---

## **7.1 - NUMBER OF OFFICERS**

The officers of the Corporation shall be a Chairman, a Secretary, and a Treasurer. The Corporation may also have, as determined by the Board, one or more Assistant Vice Chairmen, Assistant Secretaries, Assistant Treasurers, or other officers. Any number of offices may be held by the same person except that neither the Secretary nor the Treasurer may serve as the Chairman.



## **7.2 – QUALIFICATION**

Any director may serve as an officer of this Corporation. Except those officers appointed in accordance with the provisions of Section 7.4 of this Article, officers shall be elected by the Board at the annual meeting of the Board, and shall serve at the pleasure of the Board, subject to the rights of any officer under any employment contract. Each officer shall hold office for renewable terms of one year.



## **7.3 - ELECTION AND TERM OF OFFICE**

Except those officers appointed in accordance with the provisions of [Section 7.4](https://github.com/ESIPFed/Governance/blob/master/Bylaws/Article%2007%20Officers/7.04%20Subordinate%20officers.md) of this Article, officers shall be elected by the Board at the annual meeting, and shall serve at the pleasure of the Board, subject to the rights of any officer under any employment contract. Each officer shall hold office for renewable terms of one year.


## **7.4 - SUBORDINATE OFFICERS**

The Board may appoint, and may authorize the Chairman to appoint, such other officers or agents as it may deem desirable, and such officers shall serve such terms, have such authority, and perform such duties as may be prescribed from time to time by the Board.


## **7.5 - REMOVAL AND RESIGNATION**

### **7.5.1**

Subject to the rights, if any, of an officer under any contract of employment, any officer may be removed, either with or without cause, by the Board, at any regular or special meeting of the Board, or by an officer on whom such power of removal may be conferred by the Board.

## **7.5.2**

Any officer may resign at any time by giving written notice to the Board or to the Chairman. Any such resignation shall take effect at the date of receipt of such notice or at any later date specified therein. Unless otherwise specified therein, the acceptance of such resignation shall not be necessary to make it effective. The above provisions of this Section shall be superseded by any conflicting terms of a contract which has been approved or ratified by the Board relating to the employment of any officer of the Corporation.


## **7.6 – VACANCIES**

Any vacancy caused by the death, resignation, removal, disqualification, or otherwise, of any officer shall be filled by the Board. In the event of a vacancy in any office other than that of Chairman, such vacancy may be filled temporarily by appointment by the Chairman until such time as the Board shall fill the vacancy. A person so appointed to a vacant office (whether appointed by the Chairman or elected by the Board) shall hold that office until the next annual meeting of the members or until his or her death, resignation or removal from office. Vacancies occurring in offices of officers appointed at the discretion of the Board may or may not be filled as the Board shall determine



## **7.7 - DUTIES OF CHAIRMAN**

The Chairman is to:

### **7.7.1**

At such time that the Corporation does not have an executive director, chief executive officer, general manager, or a person having the general duties of any of them, subject to the control of the Board be the chief executive officer of the Corporation;

### **7.7.2**

Preside at all meetings of the Board. 

### **7.7.3**

Except as otherwise expressly provided by law, by the Articles of Incorporation, or by these bylaws, in the name of the Corporation, execute such deeds, mortgages, bonds, contracts, checks, or other instruments which may from time to time be authorized by the Board; and

### **7.7.4**

Perform all other duties incident to his or her office and such other duties as may be required by the Act, by the Articles of Incorporation of this Corporation, or by these bylaws, or which may be prescribed from time to time by the Board.



## **7.8 - DUTIES OF SECRETARY**

The Secretary is to:

### **7.8.1**

Certify and keep, or cause to be kept, at the principal office of the Corporation the original, or a copy, of the Articles of Incorporation and of these bylaws, as amended or otherwise altered to date;

### **7.8.2**

Keep, or cause to be kept, at the principal office of the Corporation or at such other place as the Board may direct, a book of minutes of all meetings, proceedings and actions of the Board and of committees of the Board as further set forth in Section 6.3.2, and of the members;

### **7.8.3**

See that all notices are duly given in accordance with the provisions of these bylaws or as required by law;

### **7.8.4**

Be custodian of the records and of the seal of the Corporation, if there is a seal, and see that the seal is affixed to all duly executed documents, the execution of which on behalf of the Corporation under its seal is authorized by law or these bylaws and by the Board;

### **7.8.5**

Exhibit or cause to be exhibited at all reasonable times to any director or member of the Corporation, or to his or her agent or attorney, on request therefor, these bylaws as amended to date, the Articles of Incorporation as amended to date, the minutes of the proceedings of the Board and committees of the Board, and the Corporation's applications for tax exemption; and

### **7.8.6**

In general, perform all duties incident to the office of Secretary and such other duties as may be required by the Act, by the Articles of Incorporation of this Corporation, or by these bylaws, or which may be assigned to him or her from time to time by the Board.



## **7.9 - DUTIES OF TREASURER**

The Treasurer is to:

### **7.9.1**

Keep and maintain, or cause to be kept and maintained, adequate and correct books and accounts of the Corporation's properties and business transactions, including accounts of its assets, liabilities, receipts, disbursements, gains and losses. Books of account shall be maintained in accordance with applicable Generally Accepted Accounting Principles;

### **7.9.2**

Send, or cause to be given, to the directors and members such financial statements and reports as are required to be given by law, by these bylaws, or by the Board;

### **7.9.3**

Exhibit at all reasonable times to any director of the Corporation, or to his or her agent or attorney, on request therefor, the books of account of the Corporation;

### **7.9.4** 

Have charge and custody of, and be responsible for, all funds and securities of the Corporation, and (i) deposit, or cause to be deposited, all money and other valuables in the name and to the credit of the Corporation with such depositories as the Board may designate, and (ii) disburse, or cause to be disbursed, the Corporation's funds as the Board may order;

### **7.9.5**

Render to the Chairman and directors, whenever requested, an account of any or all of his or her transactions as Treasurer, and of the financial condition of the Corporation;

### **7.9.6**

Prepare, or cause to be prepared, and certify, or cause to be certified, the financial statements to be included in any required reports;

### **7.9.7**

In general, perform all duties incident to the office of Treasurer and such other duties as may be required by the Act, by the Articles of Incorporation of the Corporation, or by these bylaws, or which may be assigned to him or her from time to time by the Board;

### **7.9.8**

If required by the Board, give the Corporation a bond in the amount and with the surety or sureties specified by the Board for faithful performance of the duties of the office and for restoration to the Corporation of all of its books, papers, vouchers, money, and other property of every kind in the possession or under the control of the Treasurer upon his or her death, resignation, retirement, or removal from office; and

### **7.9.9**

Provide, or cause to be provided, to the public, all filings required to be disclosed and made generally available to the public in the form or forms required by the Internal Revenue Service and all other tax regulation and charitable solicitation regulation authorities, or by statute.



## **7.10 - COMPENSATION**

Officers shall serve without compensation.


