---
title: "Article 6: Meetings of the Board"
---

## **6.1 - REGULAR AND ANNUAL MEETINGS**

### **6.1.1**

Regular meetings of the directors shall be held two times per year at a place and time to be determined by the Board. The January regular meeting of the year shall be the annual meeting.

### **6.1.2**

At the annual meeting the Board shall undertake the election of officers and the transactions of other business.


## **6.2 - SPECIAL MEETINGS**

Special meetings of the Board may be called by the Chairman, a Vice Chairman, the Secretary, or by any two directors, and such meetings shall be held at the place, within or outside the State of District of Columbia, designated by the person or persons calling the meeting, or in the absence of such designation, at the principal office of the Corporation.


## **6.3 – MINUTES**

### **6.3.1**

The Board shall be responsible for recording, approving and maintaining minutes of the proceedings of the meeting of the Board, of committees of the Board and, if the Corporation has members, of meetings of the members. The Secretary shall take the minutes of Board and members' business meetings. In the event the Secretary is not in attendance at a meeting, and at all committee meetings, the chair of such meeting shall designate a person to record the minutes of the meeting.

## **6.3.2**

A book of minutes of all meetings, proceedings and actions of the Board and of committees of the Board must be maintained at the Corporation's principal office or at such other place as the Board may direct. The minutes of meetings must include: the time and place that the meeting was held; whether the meeting was annual, general, or special, and, if special, how authorized; how notice was given and to whom; the names of the persons present at the Board and committee meetings; the actions taken and decisions made by the Board at that meeting, including the number of votes for, against and in abstention of each such action or decision, and may include how each director voted on such action or decision. The book of minutes may be maintained in electronic form provided that they can be printed at any time.



## **6.4 - PLACE OF MEETINGS**

### **6.4.1**

Meetings of the Board may be held at any place within or outside District of Columbia that has been designated by resolution of the Board or in the notice of the meeting, or if not so designated, at the principal office of the Corporation.

### **6.4.2**

Any director may participate in a meeting, and any meeting of the Board may be held by, conference telephone, video screen or other transmission, provided the requirements specified below are met. A director who participates in a meeting by such means shall be considered present in person for that meeting.

   **6.4.2.1** - In the case of a meeting held by conference telephone or video screen, all directors participating in the meeting are able to hear one another.  
   **6.4.2.2** - In the case of other electronic transmission,  
      **6.4.2.2.1** - Each director participating in the meeting can communicate with all other members concurrently, and  
      **6.4.2.2.2** - Each director is provided the means of participating in all matters before the Board, including, without limitation, the capacity to propose or to interpose an objection to a specific action to be taken by the Corporation.


## **6.5 - NOTICE OF MEETINGS**

### **6.5.1**

Notices of Board meetings are valid if made by:

(i)	First class mail, postage prepaid;  
(ii)	Personal delivery of a written notice;  
(iii)	Delivery by overnight courier or private delivery service that can be and is confirmed;  
(iv)	Telephone, including a voice messaging system or other technology designed to record and communicate messages, either directly to the director or to a person at the director’s office or home who would reasonably be expected to communicate that notice promptly to the director;  
(v)	Email; or  
(vi)	Other electronic means.

### **6.5.2**

Notice of regular meetings need not be given if fixed by a resolution of the Board that is noted in minutes distributed to all directors. Otherwise, notice of regular meetings will be valid if made no less than 14 days prior to the date of the meeting. Notice of special meetings shall be given seven days before the time set for the meeting, if practical, but in no event less than 24 hours prior to the date and time of the meeting.

### **6.5.3**

All notices of Board meetings shall be given or sent to the director’s address, telephone number or email address as shown on the Corporation’s records.

### **6.5.4**

Notice of the time and place of holding an adjourned regular or special meeting shall be given to directors who were absent from the original meeting.


## **6.6 - CONTENTS OF NOTICE**

Notice of meetings not herein dispensed with shall specify the place (if other than the Corporation’s principal office), day and hour of the meeting. Notice of special meetings must set forth the purpose of the meeting and no business other than that set forth in the notice may be conducted at that meeting.


## **6.7 - WAIVER OF NOTICE AND CONSENT TO HOLDING MEETINGS**

### **6.7.1**

Notice of a meeting of the Board need not be given to any director who:

   **6.7.1.1** - Either before or after the meeting:  
      **6.7.1.1.1** - Signs a waiver of notice;  
      **6.7.1.1.2** - Signs a written consent to the holding of the meeting;  
      **6.7.1.1.3** - Approves of the minutes of the meeting; or  
   **6.7.1.2** - Attends the meeting and who, before or at the beginning of the meeting, does not protest the lack of proper notice to him or her.

### **6.7.2**

The waiver of notice or consent need not specify the purpose of the meeting. All such waivers, consents, and approvals shall be filed with the corporate records or made a part of the minutes of the meetings.



## **6.8 - QUORUM FOR MEETINGS**

### **6.8.1**

A majority of the directors then in office shall constitute a quorum for the transaction of any business except adjournment.

## **6.8.2**

If during a meeting at which a quorum was initially present some directors leave rendering the meeting without a quorum, the Board or committee may continue to transact business so long as any action taken or decision made is approved by at least the number of directors required to take action if a quorum were present.

## **6.8.3**

Except as otherwise provided in these bylaws (including, without limitation, Subsection 6.8.2, above) in the Corporation's Articles of Incorporation, or by law, no business shall be considered by the Board at any meeting at which a quorum, as defined above, is not present. The only motion which is permitted at a meeting at which a quorum is not initially present is a motion to adjourn. A majority of the directors present at such meeting may adjourn from time to time until the time fixed for the next regular meeting of the Board.


## **6.9 - MAJORITY ACTION AS BOARD ACTION**

The Board may act by approving a resolution properly set before the Board by the affirmative vote of a majority of the directors present at a duly held meeting at which a quorum is present (subject to the more stringent provisions of these bylaws or the Act including, without limitation, provisions relating to (i) approval of contracts or transact ions in which a director has a direct or indirect material financial interest, (ii) approval of certain transact ions between corporations having common directorships, (iii) creation of, and appointment to, committees of the Board, and (iv) indemnification of directors).


## **6.10 - CONDUCT OF MEETINGS**

The Chairman of the Corporation shall preside at meetings of the Board or, in his or her absence, the Vice Chairman of the Corporation or, in the absence of each of these persons, a person chosen by a majority of the directors present at the meeting. The Secretary of the Corporation shall act as Secretary of all meetings of the Board, provided that, in his or her absence, the presiding officer shall appoint another person to act as Secretary of the meeting.


## **6.11 - ACTION BY UNANIMOUS WRITTEN CONSENT WITHOUT MEETING**

Any action required or permitted to be taken by the Board may be taken without a meeting if each director signs a consent in the form of a record describing the action to be taken and delivers it to the Corporation.


