---
title: "Article 3: Members"
---

## **3.1 - QUALIFICATION AND CLASSES OF MEMBERSHIP**
 
### **3.1.1** 

The Corporation shall have voting members, all of which shall be organizations. From time to time at its discretion, the Board may determine qualifications for one or more categories of membership. All members shall have the same voting rights. 

### **3.1.2** 

In addition, the Corporation may have one or more categories of nonvoting associates (who may be referred to as members) as determined from time to time by the Board.

### **3.1.3** 

Unless otherwise specifically set forth, throughout these bylaws, the terms "member" and "member organization" (which may be used interchangeable"), and all rights and benefits afforded members, refers solely to member organizations (as described by Section 3.1.1.) having the right to vote on matter set before the membership. 


## **3.2 - RIGHTS OF MEMBERSHIP**

All member organizations in good standing shall have the right to vote, as set forth in these bylaws, on the election of directors, the disposition of all or substantially all of the assets of the Corporation, any merger and its principal terms and any amendment of those terms, any election to dissolve the Corporation, and all rights afforded members under the District of Columbia Nonprofit Corporation Act (the "Act"). Each member shall appoint a representative (each, a "Member Representative") who shall have the exclusive right to cast his or her respective member's votes on all matters set before the membership. 


## **3.3 - MEMBERS IN GOOD STANDING**

Members who are not suspended shall be members in good standing.


## **3.4 - NON-LIABILITY OF MEMBERS**

Member organizations shall not, as such, be organizationally liable, a Member Representatives shall not be personally liable for the acts, debts, liabilities, or obligations of the Corporation.


## **3.5 - RESIGNATION OF MEMBERSHIP**

A member may resign from membership at any time.


## **3.6 - TERMINATION OF MEMBERSHIP**

A membership shall terminate on occurrence of any of the following events:

### **3.6.1**

The member organization's failure to remain an active member based on the definition of active member in the Policies and Procedures Document;

### **3.6.2**

Any event that renders the member ineligible for membership, or failure to satisfy membership qualifications; or

### **3.6.3**

Termination of membership under Section 3.7 of this Article based on the good faith determination by the Board, or a committee or person authorized by the Board to make such a determination, that the member has failed in a material and serious degree to observe the rules of conduct of the Corporation, or has engaged in conduct materially and seriously prejudicial to the Corporation's purposes and interests.


## **3.7 - PROCEDURES FOR TERMINATION AND SUSPENSION OF MEMBERSHIP**

If grounds appear to exist for suspending or terminating a member under Section 3.7 of this Article, the following procedure shall be followed:

### **3.7.1**

The Board shall give the member at least 30 days' prior notice of the proposed suspension or termination and the reasons for the proposed suspension or termination. Notice shall be given by any method reasonably calculated to provide actual notice. Notice given by mail shall be sent by priority or registered mail to the member's last address as shown on the Corporation's records.

### **3.7.2**

The member shall be given an opportunity to be heard, either orally or in writing, at least five days before the effective date of the proposed suspension or termination. The hearing shall be held, or the written statement considered, by the Board or by a committee or person authorized by the Board to determine whether the suspension or termination should occur.

### **3.7.3**

Notwithstanding anything to the contrary, the Board may adopt rules that immediately suspend a member's rights of membership if such member violates the ESIP Code of Conduct as described in the Policies and Procedures Document.



## **3.8 - TRANSFER OF MEMBERSHIP**

No membership or right arising from membership shall be transferred.


## **3.9 - MEETINGS OF MEMBERS**
 
### **3.9.1**

For purposes of those bylaws, the term "members' business meeting" shall mean a "meeting of members" as that term is used in the Act. 
 
### **3.9.2**

The corporation's January Meeting and July Meeting are not "meetings of members" as that term is used in the Act. Member's business meetings may take place concurrent with the January and July Meetings.

### **3.9.3**

An annual members' business meeting shall be held each year at the regularly scheduled January meeting unless the Board fixes another date or time and so notifies members as provided in [Section 3.11](https://github.com/ESIPFed/Governance/blob/master/Bylaws/Article%2003%20Members/3.11%20Notice%20of%20meetings.md) of this Article. At the annual meeting, directors shall be elected and other proper business may be transacted, subject to [Section 3.11](https://github.com/ESIPFed/Governance/blob/master/Bylaws/Article%2003%20Members/3.11%20Notice%20of%20meetings.md) of this Article.



## **3.10 - SPECIAL MEETINGS**

### **3.10.1**

The Board, the Chairman of the Board, or 10 percent or more of the voting power of the members, may call a special members' business meeting for any lawful purpose at any time.

### **3.10.2**

A special members' business meeting called by any member entitled to call a meeting (other than the Board) pursuant to Section 3.10.1 shall be called by written request, specifying the general nature of the business proposed to be transacted, and submitted to the Chairman, any Vice Chairman or the Secretary of the Corporation. The officer receiving the request shall cause notice to be given promptly to the members entitled to vote, stating that a meeting will be held at a specified time and date fixed by the Board.

### **3.10.3**

No business other than the business that was set forth in the notice of the meeting may be transacted at a special meeting.


## **3.11 - NOTICE OF MEETINGS**

### **3.11.1**

Whenever members are required or permitted to take any action at a meeting, a written notice of the meeting shall be given to each member entitled to vote at that meeting. The notice shall specify the place, date and time of the meeting. For the annual meeting, the notice shall state the matters that the Board, at the time notice is given, intends to present for action by the members. For a special meeting, the notice shall state the general nature of the business to be transacted and shall state that no other business may be transacted. The notice of any meeting at which directors are to be elected shall include the names of all persons who are nominees when notice is given.

### **3.11.2**

Approval by the members of any of the following proposals, other than by unanimous approval of those entitled to vote, is valid only if the notice or written waiver of notice states the general nature of the proposal or proposals:

   **3.11.2.1** - Removing a director;  
   **3.11.2.2** - Filling vacancies on the Board;  
   **3.11.2.3** - Amending the Articles of Incorporation;  
   **3.11.2.4** - Electing to wind up and dissolve the Corporation;  
   **3.11.2.5** - Approving a plan of merger; or  
   **3.11.2.6** - Approving a membership exchange.

### **3.11.3**

Notice of any members’ business meeting shall be in writing and shall be given at least 10 but no more than 60 days before the meeting date. The notice shall be given either personally, or by first class, registered, or certified mail, electronic transmission, or by other means of written communication, charges prepaid, and shall be addressed to each member entitled to vote, at the address or email address of that member as it appears on the books of the Corporation or at the address given by the member to the Corporation for purposes of notice. Provided, however, that any member may revoke authorization to receive notices from the Corporation by email. Such revocation shall be deemed to occur if:

   **3.11.3.1** - The Corporation is unable to deliver two consecutives notices or other communications to the member sent by email, or  
   **3.11.3.2** - The secretary or any other person responsible for giving notice via email becomes aware of the inability of the member to receive emails.


## **3.12 - RECORD DATE**

### **3.12.1**

For purposes of establishing the members entitled to receive notice of any meeting, entitled to vote at any meeting, entitled to vote by written ballot, or entitled to exercise any rights in any lawful action, the Board of Directors may, in advance, fix a record date. The record date for the following actions will be fixed as follows:

  **3.12.1.1** - Sending notice of a meeting shall be no more than 60 nor less than 10 days before the date of the meeting;  
  **3.12.1.2** - Voting at a meeting shall be no more than 70 days before the date of the meeting;  
  **3.12.1.3** - Voting by written ballot shall be no more than 70 days before the day on which the first written ballot is mailed or solicited; and  
  **3.12.1.4** - Taking any other action shall be no more than 70 days before that action.

### **3.12.2**

If not otherwise fixed by the Board, the record date for determining members entitled to receive notice of a members’ business meeting shall be the next business day preceding the day on which notice is given or, if notice is waived, the next business day preceding the day on which the meeting is held. If not otherwise fixed by the Board, the record date for determining members entitled to vote at the meeting shall be the day on which the meeting is held.

### **3.12.3**

If not otherwise fixed by the Board, the record date for determining members entitled to vote by written ballot shall be the day on which the first written ballot is mailed or solicited.

### **3.12.4**

If not otherwise fixed by the Board, the record date for determining members entitled to exercise any rights with respect to any other lawful action shall be the date on which the Board adopts the resolution relating to that action, or the 70th day before the date of that action, whichever is later.

### **3.12.5**

For purposes of [Section 3.19](https://github.com/ESIPFed/Governance/blob/master/Bylaws/Article%2003%20Members/3.19%20Adjournment%20and%20notice%20of%20adjourned%20meetings.md) of this Article, a person holding a membership at the close of business on the record date shall be a member of record.

### **3.12.6**

A determination of members entitled to notice of or to vote at a meeting of the members shall be effective for any adjournment of the meeting unless the Board of Directors fixes a new record date, which it shall do if the meeting is adjourned to a date more than 120 days after the date fixed for the original meeting.

### **3.12.7**

If a court orders a meeting adjourned to a date more than 120 days after the date fixed for the original meeting, it may provide that the original record date continues in effect or it may fix a new record date.


## **3.13 - MEMBERS LIST FOR MEETINGS**

### **3.13.1**

After fixing a record date for a meeting, the Corporation shall prepare an alphabetical list of the names of all its members that are entitled to notice of that meeting of the members. The list shall show the address of and number of votes each member is entitled to cast at the meeting.

### **3.13.2**

The list of members shall be available for inspection by any member, beginning two business days after notice of the meeting is given for which the list was prepared and continuing through the meeting, at the Corporation’s principal office or at a place identified in the meeting notice in the city where the meeting will be held.

### **3.13.3**

Refusal or failure to prepare or make available the list of members shall not affect the validity of action taken at the meeting.


## **3.14 – QUORUM**

The Member Representatives present at any duly held members' business meeting shall constitute a quorum for the transaction of business at said members' business meeting. Attendance for the purpose of establishing a quorum shall be made in person or via teleconference by a Member Representative, provided that any meeting held by teleconference must allow Member Representatives the opportunity to read or hear the proceedings substantially concurrently with their occurrence, vote on matters submitted to the members, pose questions, and make comments.



## **3.15 – VOTING**

### **3.15.1**

Subject to the Act, all members in good standing on the record date shall be entitled to vote at any members' business meeting.

### **3.15.2**

The Member Representative of each member entitled to vote may cast one vote on each matter submitted to a vote of members.

### **3.15.3**

Voting may be by voice or by ballot, except that any election of directors must be by ballot if demanded before the voting begins by any member eligible to vote at the meeting. The Board may provide for members to vote by ballot via electronic mail (i.e., email) or electronic message board or network, but only as follows:

   **3.15.3.1** - Member Representatives may vote via email when their email is directed to the email address that the Corporation has provided from time to time to members for sending such communications to the Corporation.  
   **3.15.3.2** - Member Representatives may vote via electronic message board or network that the Corporation has designated for those communications, and which transmission shall be validly delivered upon the posting.  
   **3.15.3.3** - Voting via email, electronic message board and network shall only be permitted and valid if the Corporation has placed in effect reasonable measures to verify that the sender is the member purporting to send the transmission and that creates a record that is capable of retention, retrieval, and review, and that may thereafter be rendered into clearly legible tangible form.  
   **3.15.3.4** - The Corporation may not send a ballot by email if the authority to communicate with the member has been revoked as set forth in Section 3.11.3.

### **3.15.4**

If a quorum is present, the affirmative vote of a majority of the voting power represented at the meeting, entitled to vote, and voting on the matter, shall be deemed the act of the members unless the vote of a greater number is required by the Act, these bylaws, or the Articles of Incorporation.


## **3.16 - WAIVER OF NOTICE**

### **3.16.1**

The transaction of any members’ business meeting, however called or noticed and wherever held, shall be as valid as though taken at a meeting duly held after standard call and notice if:

   **3.16.1.1** - A quorum is present, and  
   **3.16.1.2** - Either before or after the meeting, each member entitled to vote, not present in person, signs a written waiver of notice, a consent to the holding of the meeting, or an approval of the minutes of the meeting. The waiver of notice, consent or approval need not specify either the business to be transacted or the purpose of the meeting except that, if action is taken or proposed to be taken for approval of any matter specified in Section 3.11.2 of this Article, the waiver of notice, consent or approval shall state the general nature of the proposal. All such waivers, consents or approvals shall be filed with the corporate records or made a part of the minutes of the meeting.

### **3.16.2**

A member’s attendance at a meeting shall constitute a waiver of notice of that meeting unless the member objects at the beginning of the meeting to the transaction of any business because the meeting was not lawfully called or convened. Attendance at a meeting is not a waiver of any right to object to the consideration of matters required to be included in the notice of the meeting but not so included, if the objection is expressly made at the meeting.


## **3.17 - ACTIONS BY UNANIMOUS WRITTEN CONSENT**

Any action required or permitted to be taken by the members may be taken without a meeting if all members consent in writing to the action. The written consent or consents shall be filed with the minutes of the meeting. The action by written consent shall have the same force and effect as a unanimous vote of the members.


## **3.18 - ACTION BY WRITTEN BALLOT**

### **3.18.1**

Any action that may be taken at any annual, regular, or special meeting of members may be taken without a meeting if the membership corporation delivers a ballot to every member entitled to vote on the matter.

### **3.18.2**

A ballot shall:

   **3.18.2.1** - Set forth each proposed action;  
   **3.18.2.2** - Be in the form of a record;  
   **3.18.2.3** - Set forth each proposed action;  
   **3.18.2.4** - Provide an opportunity to vote for, or withhold a vote for, each candidate for election as a director; and  
   **3.18.2.5** - Provide an opportunity to vote for or against each other proposed action.

### **3.18.3**

Approval by ballot pursuant to this section of action other than election of directors shall be valid only when the number of votes cast by ballot equals or exceeds the quorum required to be present at a meeting authorizing the action, and the number of approvals equals or exceeds the number of votes that would be required to approve the matter at a meeting at which the total number of votes cast was the same as the number of votes cast by ballot.

### **3.18.4**

All solicitations for votes by ballot shall:

   **3.18.4.1** - Indicate the number of responses needed to meet the quorum requirements;  
   **3.18.4.2** - State the percentage of approvals necessary to approve each matter other than election of directors; and  
   **3.18.4.3** - Specify the time by which a ballot must be received by the membership corporation in order to be counted.

### **3.18.5**

A ballot shall not be revoked. 


## **3.19 - ADJOURNMENT AND NOTICE OF ADJOURNED MEETINGS**

Any members’ business meeting, whether or not a quorum is present, may be adjourned from time to time by the vote of the majority of the members represented at the meeting. When a members' business meeting is adjourned to another time or place, notice need not be given of the adjourned meeting if the time and place to which the meeting is adjourned are announced at the meeting at which adjournment is taken. If after adjournment, a new record date is fixed for notice or voting, a notice of the adjourned meeting shall be given to each member who, on the record date for notice of the meeting, is entitled to vote at the meeting. At the adjourned meeting the Corporation may transact any business that might have been transacted at the original meeting.


