---
title: "Article 9: Execution of Instruments, Deposits and Funds"
---

## **9.1 - EXECUTION OF INSTRUMENTS**

Except as otherwise provided in these bylaws, the Board may by resolution authorize any officer or agent of the Corporation to enter into any contract or execute and deliver any instrument in the name of and on behalf of the Corporation, and such authority may be general or confined to specific instances. Unless so authorized, no officer, agent, or employee shall have any power or authority to bind the Corporation by any contract or engagement or to pledge its credit or to render it liable monetarily for any purpose or in any amount.


## **9.2 - CHECKS AND NOTES**

The Board shall determine who shall be authorized from time to time on the Corporation's behalf to sign checks, drafts and other orders for payment of money. Such authority may be general or confined to specific instances.


## **9.3 – DEPOSITS**

All funds of the Corporation shall be deposited from time to time to the credit of the Corporation in such banks, trust companies, or other depositories as the Board may select.


## **9.4 – GIFTS**

The Board may accept on behalf of the Corporation, any contribution, gift, bequest, or devise for the charitable or public purposes of this Corporation.



## **9.5 - REPRESENTATION OF SHARES OF OTHER CORPORATIONS**

The Chairman or any other officer or officers authorized by the Board are each authorized to vote, represent, and exercise on behalf of the Corporation all rights incident to any and all shares of any other Corporation. The authority herein granted may be exercised either by any such officer in person or by any other person authorized to do so by proxy or power of attorney duly executed by said officer. Notwithstanding the above, the Board shall vote or direct the Chairman with respect to matters involving this Corporation 's membership in other nonprofit corporations.


