---
title: "3.3F Committee Budget Request Policy"
date: 2026-01-27
---

 ### ESIP Policy on Committee and Working Group Proposals and Supporting Budget Requests

 ESIP makes funds available to its committees and working groups through an
 annual budget process (funds permitting). The following details the guiding
 principles and required elements for any budget request submitted to ESIP's
 Finance and Appropriations Committee.

## 3.3f.1. Guiding Principles for Committee/Working Group Budget Proposals

### 3.3f.1.1.

All Committees and Working Groups may submit budget proposals. A coordinated
Committee or Working Group proposal request is offered by the Chair and should
be supported by a majority of the members of the group.

### 3.3f.1.2.

The Committee or Working Group proposal request should describe how the work to
be supported by the requested funds leverages and augments existing volunteer
efforts by group members.

### 3.3f.1.3.

The Finance and Appropriations Committee will review all committee and working
group proposals and respond to the committees and working groups with tentative
decisions. The Executive Committee will review recommendations of the Finance
and Appropriations Committee, and if it agrees with the recommendations, will
initiate appropriate actions to allocate funds.

### 3.3f.1.4.

Committee and Working Group proposals will be evaluated on their direct
long-term benefit to ESIP. Proposals should align with ESIP's strategic
interests and should emphasize collaborations that provide long-term benefits to
the ESIP community.

### 3.3f.1.5.

Committees and Working Groups should consider proposals that leverage
collaborative activities.

## 3.3f.2. Required Elements

### 3.3f.2.1.

Funded activities will advance one or more identified ESIP community interests,
such as the following examples:

- ESIP community-level technical solutions that ESIP partners can collectively
  develop and utilize.
- Travel support to represent an ESIP entity at a professional meeting.
- Short-term projects that can be sustained beyond the funded period.

### 3.3f.2.2.

Funded activities will align with ESIP's strategic plan.

- Budget proposals will describe how each proposed activity will meet strategic
  priorities.
- Proposed activities will be mapped to specific strategic plan goals or
  objectives.
- Budget proposals will rank individual funding requests as Essential,
  Important, or Desired.

### 3.3f.2.3.

Committee and Working Group budgets will be based on the deliberations of the
entire Committee/Working Group, including open competition among the membership.

- Notice of budget deliberations must be sent by the Committee/Working Group
  chair to the membership at least 14 days prior to such deliberations.

### 3.3f.2.4.

Funded activities and their responsible Committee or Working Group will submit
required reports to the Executive Committee.

- Reports will be submitted semi-annually, 30 days prior to the January and July
  meetings.
- Reports will document milestones, money spent, and finished products,as
  appropriate.
- Report formats can vary, as long as the required information is provided
  (e.g., committee or working group wiki page, blog post).

### 3.3f.2.5.

Committees and Working Groups that are funded will actively participate in
semi-annual meetings during the funded period. Examples of participation include
Collaboration Area poster, poster during the evening reception, workshop, and
demonstration.

### 3.3f.2.6.

Funding activities shall be consistent with the guidelines established, and/or
regulations contained, in cooperative agreements and other federal funding
sources, of which the Foundation for ESIP is a recipient.

## 3.3f.3. General Provisions

-  Support for projects will be based on an approved fee for services and not on
   an hourly rate.
-  No overhead can be claimed on funded Committee and Working Group activities.
-  Unspent Committee or Working Group budget resources will revert to the
   general fund, at the end of the fiscal year.
-  Clusters do not have annual budgets. However, Clusters can submit "as needed
   budgets" for [*"special
   projects."*](https://docs.google.com/document/d/1b3ZZ7pvDHsx9Qf8wv-9VXi8IEdm7MLSmBNGQ_Elk1b0/edit#)
-  Technical innovations that have limited appeal to the broad ESIP community
   should be submitted to FUNding Friday competitions.
-  Committee and Working Group proposals should benefit the broader ESIP
   community and work toward a sustainable infrastructure for ESIP and its
   partners.
-  Committee and Working Group budget requests are due annually on August 15.
-  ESIP does not pay stipends and/or gifts to volunteers.  ESIP participants are
   volunteers, and in order to comply with the Volunteer Protection Act, ESIP
   cannot pay stipends.  Doing so would take away protections given to
   volunteers under the Volunteer Protection Act. An exception to this policy
   would be cases where the payment of stipends is specifically stated in ESIP's
   cooperative agreement and/or grants with a funder.  In this case, the money
   will be paid from the budget set forth in the agreement and not from
   committee budgets.

---
This Policy was approved by the Board of Directors of ESIP on October 17, 2017.
